services:
  app:
    build: .
    environment:
      - SMALRUBY3_HOST=0.0.0.0
      - PORT=8601
      - NODE_ENV
      - DEBUG
      - GOOGLE_CLIENT_ID
      - GOOGLE_API_KEY
      - GTM_ID
      - GTM_ENV_AUTH
      - MESH_GRAPHQL_ENDPOINT
      - MESH_API_KEY
      - MESH_AWS_REGION
      - MESH_DATA_UPDATE_INTERVAL_MS
      - MESH_EVENT_BATCH_INTERVAL_MS
      - MESH_NETWORK_FILTER
    working_dir: /app
    shm_size: '4gb'
    command: npm start
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: smalruby3-editor_root_npm
        target: /root/.npm
      - type: volume
        source: smalruby3-editor_root_cache
        target: /root/.cache
      - type: volume
        source: smalruby3-editor_node_modules
        target: /app/node_modules
    ports:
      - 0.0.0.0:8601:8601
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  infra:
    build:
      context: .
      dockerfile: infra/Dockerfile
    working_dir: /app/infra/smalruby-mesh-v2
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: smalruby3-editor_infra_mesh_v2_node_modules
        target: /app/infra/smalruby-mesh-v2/node_modules
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - STAGE
      - MESH_SECRET_KEY
      - MESH_HOST_HEARTBEAT_INTERVAL_SECONDS
      - MESH_HOST_HEARTBEAT_TTL_SECONDS
      - MESH_MEMBER_HEARTBEAT_INTERVAL_SECONDS
      - MESH_MEMBER_HEARTBEAT_TTL_SECONDS
      - MESH_MAX_CONNECTION_TIME_SECONDS
      - MESH_EVENT_TTL_SECONDS
      - MESH_POLLING_INTERVAL_SECONDS

volumes:
  smalruby3-editor_root_npm:
  smalruby3-editor_root_cache:
  smalruby3-editor_node_modules:
  smalruby3-editor_infra_mesh_v2_node_modules:
