# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
  gem "rake-compiler", "~> 1.0"
  gem "standard", "~> 1.0"
end
