# frozen_string_literal: true

require "rake/testtask"
require "rake/extensiontask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

Rake::ExtensionTask.new("smalruby3_imageutil") do |ext|
  ext.lib_dir = "lib/smalruby3"
end

task default: %i[compile test]
