# frozen_string_literal: true

require_relative "lib/smalruby3/version"

Gem::Specification.new do |spec|
  spec.name = "smalruby3"
  spec.version = Smalruby3::VERSION
  spec.authors = ["Kouji Takao"]
  spec.email = ["kouji.takao@gmail.com"]

  spec.summary = "Scratch-compatible Ruby runtime for Smalruby"
  spec.description = "A Ruby gem that provides a Scratch VM-compatible runtime, " \
                     "allowing Ruby scripts generated by smalruby3-editor to run " \
                     "natively on the desktop using SDL2."
  spec.homepage = "https://github.com/smalruby/smalruby3-editor"
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.3"

  spec.files = Dir["lib/**/*.rb", "lib/**/*.json", "ext/**/*.{rb,rs,toml}", "assets/**/*", "LICENSE", "README.md"]
  spec.require_paths = ["lib"]
  spec.extensions = ["ext/smalruby3_resvg/extconf.rb"]

  spec.add_dependency "ruby-sdl2", "~> 0.3"
  spec.add_dependency "rb_sys", "~> 0.9"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://github.com/smalruby/smalruby3-editor/tree/develop/ruby/smalruby3"
end
